### ISSUE TITLE
Expose port range

### ISSUE THREAD

**Issue by julien-duponchelle** [gcasella/gns3-docker#3]
Actually the container expose only the port 3080 used to control GNS3.

But if you want to connect from the outside to the console you need to expose:
_console_start_port_range_ to _console_end_port_range_ and _allow_console_from_anywhere_
https://github.com/gcasella/gns3-docker/blob/master/gns3_server.conf

If you want to allow to make network between devices on your local computer to device on the container you need to expose:
_udp_start_port_range_ to _udp_end_port_range_

**Comment by gcasella** [comment]
Hey Julien,

That's funny, because when I did my testing, I started a topology with 3 IOU devices. And a qemu IOSv router and was able to console to them just fine while just exposing port 3080.

I will test again and take a look.

On 7 Jul 2016 3:09 a.m., Julien Duponchelle notifications@github.com wrote:

Actually the container expose only the port 3080 used to control GNS3.

But if you want to connect from the outside to the console you need to expose:
console_start_port_range to console_end_port_range and allow_console_from_anywhere
https://github.com/gcasella/gns3-docker/blob/master/gns3_server.conf

If you want to allow to make network between devices on your local computer to device on the container you need to expose:
udp_start_port_range to udp_end_port_range

**Comment by gcasella** [comment]
@noplay not needed.
here's a screenshot of me connecting to my devices without needing to expose the port range;
[http://imgur.com/O0jnk5L](url)
